### ISSUE TITLE
Doubt execution

### ISSUE THREAD

**Issue by tXambe** [root-tanishq/userefuzz#14]
Hello,

when I run this script detect a SQLi 

```
Payload =>  "XOR(if(now()=sysdate(),sleep(10),0))XOR"
```
but how I know where inject this payload ?

A greting and thanks

**Comment by root-tanishq** [comment]
The tool injects the SQLI payloads in the header the tool will specify which headers the tool is currently injecting but by Default it injects in User-Agent , X-Forwarded-For  and Referer header
and also please consider asking doubt questions on twitter or linkedin as an new issue gets opened due to this
I am closing this issue if you still founds issue feel free to message me at https://twitter.com/root_tanishq
